title: KorGE - Modern Multiplatform Game Engine for Kotlin
baseurl: ""
url: ""

markdown: kramdown

collections:
  versions:
    sort_by: order
  starterkits:
    sort_by: order
    output: true
    permalink: /starterkits/:title/
  modules:
    sort_by: order
    output: true
    permalink: /module/:title/
  repotags:
    sort_by: order
    output: true
    permalink: /repotags/:title.json
