title: KorGE - Modern Multiplatform Game Engine for Kotlin
url: "https://store.korge.org"

markdown: kramdown

collections:
  versions:
    sort_by: order
  starterkits:
    sort_by: order
    output: true
    permalink: /starterkits/:title/
  showcases:
    sort_by: order
    output: true
    permalink: /showcases/:title/
  modules:
    sort_by: order
    output: true
    permalink: /module/:title/
  repotags:
    sort_by: order
    output: true
    permalink: /repotags/:title.json
  sfx:
    sort_by: order
    output: true
    permalink: /sfx/:title/
